// ============================================================
// VANSHAWALI — Family Data (Sample: Sharma Parivar)
// ============================================================

const FAMILY_DATA = {
  meta: {
    familyName: "शर्मा परिवार",
    origin: "जयपुर, राजस्थान",
    since: "1944",
  },

  members: [
    // ── GENERATION 0: PITA-MAH (Great-Grandparents) ──────
    {
      id: "g0_pita",
      name: "राम लाल शर्मा",
      gender: "male",
      relation: "परदादा",
      generation: 0,
      birth: "1920",
      death: "1994",
      place: "जयपुर",
      emoji: "👴",
      bio: "एक सरल और ईमानदार किसान, जिन्होंने अपने परिवार को संस्कारों की नींव दी। उनकी वीणा वादन की कला पूरे गाँव में प्रसिद्ध थी।",
      spouseId: "g0_mata",
      childIds: ["g1_dada", "g1_kaka"],
      color: 0xffd60a,
    },
    {
      id: "g0_mata",
      name: "सावित्री देवी",
      gender: "female",
      relation: "परदादी",
      generation: 0,
      birth: "1924",
      death: "2001",
      place: "अजमेर",
      emoji: "👵",
      bio: "ममता की मूरत, सावित्री देवी ने पूरे परिवार को एकजुट रखा। उनके हाथ की दाल-बाटी की सुगंध आज भी यादों में बसी है।",
      spouseId: "g0_pita",
      childIds: ["g1_dada", "g1_kaka"],
      color: 0xffd60a,
    },

    // ── GENERATION 1: DADA-DADI ──────────────────────────
    {
      id: "g1_dada",
      name: "महेश शर्मा",
      gender: "male",
      relation: "दादा",
      generation: 1,
      birth: "1948",
      death: "2018",
      place: "जयपुर",
      emoji: "👴",
      bio: "सरकारी स्कूल में अध्यापक रहे। 35 वर्षों तक सैकड़ों बच्चों को शिक्षा दी। उन्हें शतरंज और कबीर के दोहे बहुत पसंद थे।",
      spouseId: "g1_dadi",
      parentIds: ["g0_pita", "g0_mata"],
      childIds: ["g2_papa", "g2_chacha"],
      color: 0x00d4ff,
    },
    {
      id: "g1_dadi",
      name: "कमला देवी",
      gender: "female",
      relation: "दादी",
      generation: 1,
      birth: "1950",
      death: null,
      place: "जयपुर",
      emoji: "👵",
      bio: "आज 74 वर्ष की आयु में भी बिल्कुल चुस्त! पूजा-पाठ और बागबानी में उनका मन रमता है। परिवार की सबसे बड़ी शक्ति।",
      spouseId: "g1_dada",
      parentIds: ["g0_pita", "g0_mata"],
      childIds: ["g2_papa", "g2_chacha"],
      color: 0x00d4ff,
    },
    {
      id: "g1_kaka",
      name: "सुरेश शर्मा",
      gender: "male",
      relation: "परदादा के छोटे बेटे",
      generation: 1,
      birth: "1952",
      death: "2010",
      place: "जोधपुर",
      emoji: "🧔",
      bio: "व्यापारी और उद्यमी। जोधपुर में कपड़े का बड़ा व्यवसाय स्थापित किया। उनकी सकारात्मकता पूरे परिवार को ऊर्जा देती थी।",
      spouseId: null,
      parentIds: ["g0_pita", "g0_mata"],
      childIds: [],
      color: 0x00d4ff,
    },

    // ── GENERATION 2: MATA-PITA ──────────────────────────
    {
      id: "g2_papa",
      name: "विजय शर्मा",
      gender: "male",
      relation: "पिता",
      generation: 2,
      birth: "1972",
      death: null,
      place: "जयपुर",
      emoji: "👨",
      bio: "सॉफ्टवेयर इंजीनियर। IIT दिल्ली से पढ़े हुए। परिवार के पहले इंजीनियर! क्रिकेट के दीवाने और एक अद्भुत पिता।",
      spouseId: "g2_mama",
      parentIds: ["g1_dada", "g1_dadi"],
      childIds: ["g3_main", "g3_bhai", "g3_didi"],
      color: 0xbf5af2,
    },
    {
      id: "g2_mama",
      name: "प्रिया शर्मा",
      gender: "female",
      relation: "माता",
      generation: 2,
      birth: "1975",
      death: null,
      place: "जयपुर",
      emoji: "👩",
      bio: "डॉक्टर (MBBS, MD)। शहर के सरकारी अस्पताल में वरिष्ठ चिकित्सक। संगीत प्रेमी — सितार बजाती हैं।",
      spouseId: "g2_papa",
      parentIds: [],
      childIds: ["g3_main", "g3_bhai", "g3_didi"],
      color: 0xbf5af2,
    },
    {
      id: "g2_chacha",
      name: "राजेश शर्मा",
      gender: "male",
      relation: "चाचा",
      generation: 2,
      birth: "1975",
      death: null,
      place: "मुम्बई",
      emoji: "👨‍💼",
      bio: "फिल्म उद्योग में प्रोडक्शन डिज़ाइनर। मुम्बई में बसे हैं। परिवार के सबसे रचनात्मक और मज़ेदार सदस्य!",
      spouseId: "g2_chachi",
      parentIds: ["g1_dada", "g1_dadi"],
      childIds: ["g3_cousin"],
      color: 0xbf5af2,
    },
    {
      id: "g2_chachi",
      name: "अनीता शर्मा",
      gender: "female",
      relation: "चाची",
      generation: 2,
      birth: "1978",
      death: null,
      place: "मुम्बई",
      emoji: "👩‍🎨",
      bio: "ग्राफिक डिज़ाइनर और चित्रकार। उनकी पेंटिंग्स मुम्बई की कई गैलरियों में प्रदर्शित हो चुकी हैं।",
      spouseId: "g2_chacha",
      parentIds: [],
      childIds: ["g3_cousin"],
      color: 0xbf5af2,
    },

    // ── GENERATION 3: HAM (Us) ────────────────────────────
    {
      id: "g3_main",
      name: "आर्यन शर्मा",
      gender: "male",
      relation: "स्वयं (मुख्य)",
      generation: 3,
      birth: "1998",
      death: null,
      place: "जयपुर / बेंगलुरु",
      emoji: "👦",
      bio: "Computer Science में B.Tech। एक Tech Startup में काम करते हैं। AI और 3D Technology में गहरी रुचि है। वंशावली के निर्माता! 🚀",
      spouseId: null,
      parentIds: ["g2_papa", "g2_mama"],
      childIds: [],
      color: 0x30d158,
      isRoot: true,
    },
    {
      id: "g3_bhai",
      name: "आकाश शर्मा",
      gender: "male",
      relation: "छोटे भाई",
      generation: 3,
      birth: "2001",
      death: null,
      place: "जयपुर",
      emoji: "🧑",
      bio: "B.Com कर रहे हैं। CA बनना चाहते हैं। फुटबॉल के खिलाड़ी और गिटार के शौकीन।",
      spouseId: null,
      parentIds: ["g2_papa", "g2_mama"],
      childIds: [],
      color: 0x30d158,
    },
    {
      id: "g3_didi",
      name: "अनन्या शर्मा",
      gender: "female",
      relation: "बड़ी बहन",
      generation: 3,
      birth: "1995",
      death: null,
      place: "दिल्ली",
      emoji: "👧",
      bio: "IAS अधिकारी। दिल्ली में तैनात। परिवार की सबसे बड़ी उपलब्धि और सबकी रोल मॉडल। 💪",
      spouseId: "g3_jija",
      parentIds: ["g2_papa", "g2_mama"],
      childIds: ["g4_bhanja"],
      color: 0x30d158,
    },
    {
      id: "g3_jija",
      name: "अमित वर्मा",
      gender: "male",
      relation: "जीजा जी",
      generation: 3,
      birth: "1993",
      death: null,
      place: "दिल्ली",
      emoji: "👨‍⚖️",
      bio: "वकील और कानूनी सलाहकार। सर्वोच्च न्यायालय में प्रैक्टिस करते हैं। किताबें पढ़ना और ट्रेकिंग पसंद है।",
      spouseId: "g3_didi",
      parentIds: [],
      childIds: ["g4_bhanja"],
      color: 0x30d158,
    },
    {
      id: "g3_cousin",
      name: "इशान शर्मा",
      gender: "male",
      relation: "चचेरे भाई",
      generation: 3,
      birth: "2000",
      death: null,
      place: "मुम्बई",
      emoji: "🧑‍🎬",
      bio: "Film School में पढ़ रहे हैं। Filmmaker बनने का सपना है। Bollywood और Hollywood दोनों के बड़े फैन।",
      spouseId: null,
      parentIds: ["g2_chacha", "g2_chachi"],
      childIds: [],
      color: 0x30d158,
    },

    // ── GENERATION 4: SANTAN (Next Gen) ──────────────────
    {
      id: "g4_bhanja",
      name: "देव वर्मा",
      gender: "male",
      relation: "भांजा",
      generation: 4,
      birth: "2022",
      death: null,
      place: "दिल्ली",
      emoji: "👶",
      bio: "परिवार का सबसे नन्हा सदस्य! अभी केवल 2 वर्ष का है। मुस्कान से पूरे घर को रोशन कर देता है। ✨",
      spouseId: null,
      parentIds: ["g3_didi", "g3_jija"],
      childIds: [],
      color: 0xff6b35,
    },
  ]
};

// Build lookup maps
FAMILY_DATA.byId = {};
FAMILY_DATA.members.forEach(m => { FAMILY_DATA.byId[m.id] = m; });
